### ISSUE TITLE
Error ”/” in the Title

### ISSUE THREAD

**Issue by tunagohan** [mom0tomo/blog-post-salvager#9]
2017/11/30 10:22:14 Error!: open ./md/2017/11/13 ( ＾∀＾) < 交換ノート ⭐️ .md: no such file or directory
exit status 1

ディレクトリとして認識してしまう疑惑
もしくは絵文字

**Comment by mom0tomo** [comment]
ʕ•́ᴥ•̀ʔ

**Comment by tunagohan** [comment]
メタキャラは置換させることで対応できることが確認できました。
のでクローズ
